/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthGoogleIndexRouteImport } from './routes/api.auth.google.index'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api.auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleIndexRoute = ApiAuthGoogleIndexRouteImport.update({
  id: '/api/auth/google/',
  path: '/api/auth/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/': typeof ApiAuthGoogleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/google/callback' | '/api/auth/google'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/google/callback' | '/api/auth/google'
  id: '__root__' | '/' | '/api/auth/google/callback' | '/api/auth/google/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleIndexRoute: typeof ApiAuthGoogleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/': {
      id: '/api/auth/google/'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleIndexRoute: ApiAuthGoogleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
